import 'dart:math';import 'package:flutter/material.dart';import 'package:flutter/scheduler.dart';import '../game/controller.dart';import '../game/painter.dart';import '../models/models.dart';import '../services/progress_store.dart';import '../widgets/ui.dart';import 'level_clear_screen.dart';
class GameScreen extends StatefulWidget{final ProgressStore store;final LevelDef level;const GameScreen({super.key,required this.store,required this.level});@override State<GameScreen> createState()=>_G();}
class _G extends State<GameScreen> with SingleTickerProviderStateMixin{late GameController g;late Ticker t;Duration last=Duration.zero;bool done=false;
 @override void initState(){super.initState();g=GameController(widget.level,widget.store.skin);t=createTicker(tick)..start();}
 void tick(Duration n){if(last==Duration.zero){last=n;return;}g.update((n-last).inMicroseconds/1e6);last=n;if(g.won&&!done){done=true;Future.delayed(const Duration(milliseconds:350),finish);}if(mounted)setState((){});}
 Future<void> finish()async{int st=1;if(g.elapsed<=widget.level.par)st++;if(g.core)st++;final r=LevelResult(st,g.elapsed,g.core);await widget.store.save(widget.level.n,r);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>LevelClearScreen(store:widget.store,level:widget.level,result:r)));}
 @override void dispose(){t.dispose();g.dispose();super.dispose();}
 @override Widget build(BuildContext c){final dx=widget.store.shake&&g.shake>0?sin(g.elapsed*90)*g.shake*5:0.0;return Scaffold(body:SafeArea(child:Column(children:[
 Row(children:[IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.close)),Expanded(child:Text('${widget.level.n.toString().padLeft(2,'0')} // ${widget.level.name}',style:const TextStyle(fontWeight:FontWeight.w900))),Text('${g.elapsed.toStringAsFixed(1)}s',style:const TextStyle(color:cyan,fontWeight:FontWeight.w900)),IconButton(onPressed:g.pause,icon:Icon(g.paused?Icons.play_arrow:Icons.pause))]),
 Expanded(child:Padding(padding:const EdgeInsets.all(10),child:Transform.translate(offset:Offset(dx,0),child:ClipRRect(borderRadius:BorderRadius.circular(18),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:GamePainter(g))),if(g.paused)overlay('PAUSED','RESUME',g.pause,cyan),if(g.dead)overlay('SYSTEM FAILURE','RETRY',(){g.restart();done=false;},red)]))))),
 Padding(padding:const EdgeInsets.symmetric(horizontal:14),child:Row(children:[Text(g.core?'◆ CORE SECURED':'◇ CORE OPTIONAL',style:TextStyle(color:g.core?orange:muted,fontSize:9,fontWeight:FontWeight.w900)),if(g.shield)const Text('   ◉ SHIELD',style:TextStyle(color:cyan,fontSize:9,fontWeight:FontWeight.w900)),if(g.slow)const Text('   ◷ SLOW',style:TextStyle(color:purple,fontSize:9,fontWeight:FontWeight.w900))])),const SizedBox(height:8),controls(),const SizedBox(height:12)])));}
 Widget overlay(String a,String b,VoidCallback f,Color col)=>Positioned.fill(child:Container(color:voidC.withOpacity(.84),child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[NeonTitle(a,size:28),const SizedBox(height:18),GButton(b,Icons.restart_alt,f,color:col)]))));
 Widget controls(){Widget b(GravityDir d,IconData i)=>Expanded(child:SizedBox(height:54,child:OutlinedButton(onPressed:()=>g.grav(d),style:OutlinedButton.styleFrom(side:BorderSide(color:g.gravity==d?widget.level.accent:muted.withOpacity(.25))),child:Icon(i,color:g.gravity==d?widget.level.accent:Colors.white))));return Padding(padding:const EdgeInsets.symmetric(horizontal:14),child:Row(children:[if(widget.level.four)...[b(GravityDir.left,Icons.arrow_back),const SizedBox(width:7)],b(GravityDir.up,Icons.arrow_upward),const SizedBox(width:7),b(GravityDir.down,Icons.arrow_downward),if(widget.level.four)...[const SizedBox(width:7),b(GravityDir.right,Icons.arrow_forward)]]));}}
