import 'dart:math';import 'package:flutter/material.dart';import '../models/models.dart';import '../widgets/ui.dart';import 'controller.dart';
class GamePainter extends CustomPainter{final GameController g;GamePainter(this.g):super(repaint:g);
 @override void paint(Canvas c,Size s){Rect rr(Rect r)=>Rect.fromLTRB(r.left*s.width,r.top*s.height,r.right*s.width,r.bottom*s.height);Offset pp(Offset p)=>Offset(p.dx*s.width,p.dy*s.height);
 c.drawRect(Offset.zero&s,Paint()..color=voidC);final grid=Paint()..color=g.level.accent.withOpacity(.05);for(double x=0;x<s.width;x+=28)c.drawLine(Offset(x,0),Offset(x,s.height),grid);for(double y=0;y<s.height;y+=28)c.drawLine(Offset(0,y),Offset(s.width,y),grid);
 for(final o in g.level.objects){final r=rr(o.rect);switch(o.kind){
 case ObjKind.wall:c.drawRRect(RRect.fromRectAndRadius(r,const Radius.circular(4)),Paint()..color=panel);c.drawRect(Rect.fromLTWH(r.left,r.top,r.width,2),Paint()..color=g.level.accent);break;
 case ObjKind.spike:spikes(c,r);break;case ObjKind.exit:c.drawRRect(RRect.fromRectAndRadius(r,const Radius.circular(8)),Paint()..style=PaintingStyle.stroke..strokeWidth=3..color=green);c.drawCircle(r.center,5,Paint()..color=green);break;
 case ObjKind.core:if(!g.used.contains('core')){c.drawCircle(r.center,r.shortestSide*.36,Paint()..color=orange..maskFilter=const MaskFilter.blur(BlurStyle.normal,8));c.drawCircle(r.center,r.shortestSide*.18,Paint()..color=Colors.white);}break;
 case ObjKind.switcher:c.drawRect(r,Paint()..color=(g.switches.contains(o.id)?green:orange).withOpacity(.55));break;
 case ObjKind.door:if(!g.switches.contains(o.link))c.drawRect(r,Paint()..color=red.withOpacity(.65));break;
 case ObjKind.portal:c.drawOval(r,Paint()..style=PaintingStyle.stroke..strokeWidth=4..color=purple);break;
 case ObjKind.breakable:if(!g.broken.contains(o.id)){c.drawRect(r,Paint()..color=orange.withOpacity(.4));c.drawLine(r.topLeft,r.bottomRight,Paint()..color=orange..strokeWidth=2);}break;
 case ObjKind.shield:if(!g.used.contains('shield${o.rect}'))pickup(c,r,cyan);break;case ObjKind.slow:if(!g.used.contains('slow${o.rect}'))pickup(c,r,purple);break;case ObjKind.burst:if(!g.used.contains('burst${o.rect}'))pickup(c,r,orange);break;}}
 for(int i=0;i<g.level.platforms.length;i++){final r=rr(g.platform(i));c.drawRRect(RRect.fromRectAndRadius(r,const Radius.circular(5)),Paint()..color=g.level.accent.withOpacity(.65));}
 for(final l in g.level.lasers){final a=pp(l.a),b=pp(l.b),on=g.laserOn(l);c.drawCircle(a,6,Paint()..color=on?red:muted);c.drawCircle(b,6,Paint()..color=on?red:muted);if(on){c.drawLine(a,b,Paint()..color=red.withOpacity(.3)..strokeWidth=10..maskFilter=const MaskFilter.blur(BlurStyle.normal,7));c.drawLine(a,b,Paint()..color=red..strokeWidth=4);c.drawLine(a,b,Paint()..color=Colors.white..strokeWidth=1.5);}}
 for(final p in g.particles)c.drawCircle(pp(p.p),2.5,Paint()..color=p.color.withOpacity(p.life.clamp(0,1)));if(!g.dead)robot(c,pp(g.player),min(s.width,s.height)*.04);}
 void pickup(Canvas c,Rect r,Color col){c.drawCircle(r.center,r.shortestSide*.4,Paint()..color=col.withOpacity(.25));c.drawCircle(r.center,r.shortestSide*.35,Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=col);}
 void spikes(Canvas c,Rect r){final n=max(1,(r.width/12).round()),w=r.width/n;final p=Path()..moveTo(r.left,r.bottom);for(int i=0;i<n;i++){p.lineTo(r.left+i*w+w/2,r.top);p.lineTo(r.left+(i+1)*w,r.bottom);}p.close();c.drawPath(p,Paint()..color=red);}
 void robot(Canvas c,Offset p,double z){final cols=[cyan,purple,orange,green],col=cols[g.skin%4];c.save();c.translate(p.dx,p.dy);double a=g.gravity==GravityDir.up?pi:g.gravity==GravityDir.left?pi/2:g.gravity==GravityDir.right?-pi/2:0;c.rotate(a);final r=RRect.fromRectAndRadius(Rect.fromCenter(center:Offset.zero,width:z,height:z),Radius.circular(z*.25));c.drawRRect(r,Paint()..color=panel);c.drawRRect(r,Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=col);c.drawCircle(Offset(0,-z*.08),z*.10,Paint()..color=Colors.white);c.drawCircle(Offset(0,-z*.08),z*.05,Paint()..color=col);if(g.shield)c.drawCircle(Offset.zero,z*.7,Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=cyan);c.restore();}
 @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>true;}
